const routes = [
  // ================= SAJHA YATAYAT ===============  //

  // Route 1 (Thankot ⇄ Airport)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["baadbhanjyan(thankot)", "kharibot", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul","naikap", "tinthana", "dhungeadda", "kalanki", "kalanki_mandir", "ravi_bhawan", "soltimod", "kalimati", "teku", "tripureshwor", "sundhara", "ratnapark", "bhrikutimandap", "bhadrakali", "maitighar", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "tinkune_chowk", "tinkune", "sinamangal", "airport"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["airport", "sinamangal", "tinkune", "tinkune_chowk", "shantinagar", "civil_hospital","new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "tripureshwor", "teku", "kalimati", "soltimod","ravi_bhawan", "kalanki_mandir", "kalanki", "dhungeadda", "tinthana", "naikap", "balkhu_pul", "satungal", "gurjudhara", "thankot_checkpost", "thankot", "kharibot", "thankot(baadbhanjyan)"] },

  // Route 2 (Naya Bus Park ⇄ Lagankhel)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["naya_bus_park", "gongabu_chowk", "samakhusi", "talim_kendra", "basundhara_chauki", "basundhara", "us_embassy", "teaching_hospital", "petrol_pump-panipokhari", "lazimpat", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "sundhara", "lainchour", "lazimpat", "panipokhari", "teaching_hospital", "us_embassy", "narayan_gopal_chowk", "basundhara", "basundhara_chauki", "talim_kendra", "samakhusi", "gongabu_chowk", "naya_bus_park"] },

  // Route 3 (Budhanilkantha ⇄ Lagankhel)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["budhanilkantha", "narayanthan_chowk-budhanilkantha", "deuba_chowk", "naya_chowk", "rudreshwor_chowk", "chapali_ghumti", "ganesh_chowk", "hattigauda_chowk", "golfutar", "neuro_hospital", "ganga_lal_hospital", "bansbari", "narayan_gopal_chowk", "chakrapat_bus_stop", "us_embassy", "teaching_hospital", "police_academy", "petrol_pump-panipokhari", "radisson_hotel", "lazimpat", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "sundhara", "RNAC", "lainchour", "lazimpat", "panipokhari", "police_academy", "teaching_hospital", "us_embassy", "narayan_gopal_chowk", "bansbari", "ganga_lal_hospital", "neuro_hospital", "golfutar", "hattigauda_chowk", "chapali", "rudreshwor_chowk", "deuba_chowk", "narayanthan_chowk-budhanilkantha", "budhanilkantha"] },

  // Route 4 (Thankot ⇄ Budhanilkantha)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["nagdhunga", "thankot(baadbhanjyan)", "kharibot", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul", "naikap", "tinthana", "dhungeadda", "kalanki", "bafal", "sitapaila", "swayambhu", "sano_bharyang", "dhungedhara", "banasthali", "balaju", "machha_pokhari", "naya_bus_park", "gongabu_chowk", "samakhusi", "talim_kendra", "basundhara_chauki", "basundhara", "narayan_gopal_chowk", "bansbari", "ganga_lal_hospital", "neuro_hospital", "golfutar", "hattigauda_chowk", "ganesh_chowk", "chapali", "rudreshwor_chowk", "deuba_chowk", "narayanthan_chowk-budhanilkantha", "budhanilkantha"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["budhanilkantha", "narayanthan_chowk-budhanilkantha", "deuba_chowk", "naya_chowk", "rudreshwor_chowk", "chapali_ghumti", "ganesh_chowk", "hattigauda_chowk", "golfutar", "neuro_hospital", "ganga_lal_hospital", "bansbari", "narayan_gopal_chowk", "basundhara", "basundhara_chauki", "talim_kendra", "samakhusi", "gongabu_chowk", "machha_pokhari", "balaju", "banasthali", "sano_bharyang", "swayambhu", "sitapaila", "bafal", "kalanki", "dhungeadda", "tinthana", "naikap", "balkhu_pul", "satungal", "gurjudhara", "thankot_checkpost", "thankot", "kharibot", "thankot(baadbhanjyan)", "nagdhunga"] },

  // Route 5 (Bungamati ⇄ Jamal)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "maitighar", "thapathali", "kupondole", "harihar_bhawan", "pulchowk", "jawalakhel", "ekantakuna", "vaisnavi_devi", "nakhu", "nakhu_pul", "phulbari_marg", "charghari", "bhaisepati_chowk", "mahila_ghar", "kalika", "khokana_dobato", "sorahkhutte", "bungamati"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["bungamati", "sorahkhutte", "khokana_dobato", "kalika", "mahila_ghar", "bhaisepati_chowk", "charghari", "phulbari_marg", "nakhu_pul", "vaisnavi_devi", "ekantakuna", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "maitighar", "RNAC", "jamal"] },

  // Route 6 (Godawari ⇄ Jamal)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "kupondole", "pulchowk", "jawalakhel", "lagankhel", "satdobato", "hattiban", "harishiddhi", "thaiba", "badegaun", "toukhel", "godawari"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["godawari", "toukhel", "badegaun", "thaiba", "harishiddhi", "hattiban", "satdobato", "lagankhel", "jawalakhel", "pulchowk", "kupondole", "sundhara", "jamal"] },

  // Route 7 (Jamal ⇄ Lele)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel", "satdobato", "chapagaun_dobato", "khumaltar", "dholahiti", "sunakothi", "thecho", "chapagaun", "pyangaun", "tahakhel", "tikabhairav", "lele"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lele", "tikabhairav", "tahakhel", "pyangaun", "chapagaun", "thecho", "sunakothi", "dholahiti", "khumaltar", "chapagaun_dobato", "satdobato", "lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "sundhara", "jamal"] },

  // Route 8 (Jamal ⇄ Dhungin)
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel", "satdobato", "gwarko", "ratamakai_chowk", "imadol_krishna_mandir", "gabisa", "rajkulo", "goalbhatta", "sanagaun", "lubhu", "lamatar", "dhungin"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["dhungin", "lamatar", "lubhu", "kwo_lachhi", "sanagaun", "goalbhatta", "imadol_kamalpokhari", "imadol_krishna_mandir", "imadol_kharibot", "kist_hospital", "gwarko", "satdobato", "lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "sundhara", "jamal"] },

  //================== LOCAL BUS ==================  //

  // Route 9 (Lagankhel ⇄ Santaneshwor)
  { vehicle: "bus", company: "Local Bus", stops: ["lagankhel", "satdobato(lagankhel side)", "satdobato(godawari side)", "dhapakhel_dobato", "sumeru_hospital", "GEMS_school", "tewa", "pashupati_temple(dhapakhel)", "tinkune(dhapakhel)", "nagdaha", "ganesh_mandir", "jharuwarashi_pipalbot_chowk", "santaneshwor_mahadev_bus_stop"] },
  { vehicle: "bus", company: "Local Bus", stops: ["santaneshwor_mahadev_bus_stop", "jharuwarashi_pipalbot_chowk", "ganesh_mandir", "nagdaha", "tinkune(dhapakhel)", "pashupati_temple(dhapakhel)", "tewa", "GEMS_school", "sumeru_hospital", "dhapakhel_dobato", "satdobato(godawari side)", "satdobato(lagankhel side)", "lagankhel"] },

  // Route 10 (Lagankhel ⇄ Tikathali)
  { vehicle: "bus", company: "Local Bus", stops: ["lagankhel", "satdobato(lagankhel side)", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko_chowk(imadol side)", "kist_hospital", "ratamakai_chowk", "imadol_pipalbot", "imadol_krishna_mandir", "manakamana_mandir(kathmandu)", "mahendra_adarsha_school", "ansari_medical", "pawan_prakriti_school", "tikathali_tinkune", "tikathali_bus_stop"] },
  { vehicle: "bus", company: "Local Bus", stops: ["tikathali_bus_stop", "tikathali_tinkune", "pawan_prakriti_school", "ansari_medical", "mahendra_adarsha_school", "manakamana_mandir(kathmandu)", "imadol_krishna_mandir", "imadol_pipalbot", "ratamakai_chowk", "kist_hospital", "gwarko_chowk(imadol side)", "gwarko", "satdobato_swimming_pool", "satdobato(lagankhel side)", "lagankhel"] },

  // ============== MAHANAGAR YATAYAT =============== //

  // Route 11 (Ringroad)
  { vehicle: "bus", company: "Mahanagar Yatayat", stops: ["gwarko", "satdobato_swimming_pool", "satdobato", "chapagaun_dobato", "talchikhel", "mahalaxmisthan", "kusunti", "ekantakuna", "nakhu", "dhobigat", "star_hospital", "sanepa", "balkhu", "advanced_college_of_engineering", "khasi_bazar", "kalanki_makalu_stop", "bafal", "sitapaila", "swayambhu", "thulo_bharyang", "sano_bharyang", "dhungedhara", "banasthali", "balaju", "machha_pokhari", "gongabu_chowk", "samakhusi", "basundhara", "chiray_hospital", "narayan_gopal_chowk", "chhapal_karkhana", "dhumbarahi", "gopi_krishna", "chabahil", "mitrapark", "jay bageshwori", "gaushala", "pashupati_temple", "tilganga_eye_hospital", "airport", "sinamangal", "sinamangal_Ooralo", "tinkune", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pul", "balkumari", "balkumari_kharibot", "royal_tulip_hotel"] },
  { vehicle: "bus", company: "Mahanagar Yatayat", stops: ["balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "koteshwor_bhaktapur_stop", "tinkune", "sinamangal_Ooralo", "sinamangal", "airport", "tilganga_eye_hospital", "pashupati_temple", "gaushala", "jay bageshwori", "mitrapark", "chabahil", "gopi_krishna", "dhumbarahi", "chhapal_karkhana", "narayan_gopal_chowk", "chiray_hospital", "basundhara", "samakhusi", "gongabu_chowk", "machha_pokhari", "balaju", "banasthali", "dhungedhara", "sano_bharyang", "thulo_bharyang", "swayambhu", "sitapaila", "bafal", "kalanki_makalu_stop", "khasi_bazar", "advanced_college_of_engineering", "balkhu", "sanepa", "star_hospital", "dhobigat", "nakhu", "ekantakuna", "kusunti", "mahalaxmisthan", "talchikhel", "chapagaun_dobato", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko"] },

  // ================= BHAKTAPUR YATAYAT =================

  // Route 12 (Bhaktapur ⇄ Kalanki)
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kaushaltar", "lockanthali", "jadibutti", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pool", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "satdobato_swimming_pool", "satdobato", "chapagaun_dobato", "talchikhel", "mahalaxmisthan", "kusunti", "ekantakuna", "nakhu", "dhobigat", "star_hospital", "sanepa", "balkhu", "advanced_college_of_engineering", "khasi_bazar", "kalanki_makalu_stop"] },
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kalanki_makalu_stop", "khasi_bazar", "advanced_college_of_engineering", "balkhu", "sanepa", "star_hospital", "dhobigat", "nakhu", "ekantakuna", "kusunti", "mahalaxmisthan", "talchikhel", "chapagaun_dobato", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko", "balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "jadibutti", "lockanthali", "kaushaltar", "gatthagar", "chardobato", "tuberculosis_hospital", "thimi", "radhe radhe", "srijan_nagar", "sallaghari", "chundevi", "suryabinayak", "jagati", "dhara", "chaymasing", "kamalbinayak"] },

  // Route 13 (Bhaktapur ⇄ Lagankhel)
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kaushaltar", "lockanthali", "jadibutti", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pool", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "satdobato_swimming_pool", "satdobato", "lagankhel"] },
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["lagankhel", "satdobato(godawari side)", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko", "balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "jadibutti", "lockanthali", "kaushaltar", "gatthagar", "chardobato", "tuberculosis_hospital", "thimi", "radhe radhe", "srijan_nagar", "sallaghari", "chundevi", "suryabinayak", "jagati", "dhara", "chaymasing", "kamalbinayak"] },

  // Route 14 (Bhaktapur ⇄ RNAC)
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kaushaltar", "lockanthali", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "sahid_gate", "RNAC"] },
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["RNAC", "ratnapark", "tudikhel", "bhrikutimandap", "singha_durbar", "supreme_court", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "lockanthali", "kaushaltar", "gatthagar", "chardobato", "tuberculosis_hospital", "thimi", "radhe radhe", "srijan_nagar", "sallaghari", "chundevi", "suryabinayak", "jagati", "dhara", "chaymasing", "kamalbinayak"] },

  // ================= NEPAL YATAYAT =================

  // Route 15 (Balkhu ⇄ HarHar Mahadev)
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["balkhu", "sanepa", "star_hospital", "dhobigat", "nakhu", "ekantakuna", "jawalakhel", "jawalakhel_chowk", "pulchowk", "harihar_bhawan", "kupondole", "kantipur_park_thapathali", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "chhapro", "pepsicola", "pepsicola_chowk", "pepsicola_town_planning", "sunrise_chowk", "suncity", "laure_chowk", "harhar_mahadev_temple", "harhar_mahadev"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["harhar_mahadev", "harhar_mahadev_temple", "laure_chowk", "suncity", "sunrise_chowk", "pepsicola_town_planning", "pepsicola_chowk", "pepsicola", "chhapro", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "thapathali", "tripureshwor", "teku", "kalimati", "gobal_ime_kuleshwor", "nabil_kuleshwor", "kitab_kalam_kuleshwor", "balkhu"] },

  // Route 16 (Kapan ⇄ Tikathali)
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["kapan", "banglamukhi_kapan", "dhaulagiri_chowk", "aani_gumba_kapan", "kharibot_faika", "sanima_bank_faika", "faika_chowk", "mandala_banquet_mahankal", "bajranagar", "mugum_gumbha_mahankal", "ramsterdam_cafe_mahankal", "mahankal", "chuchhepati", "shanti_goreto_chabahil", "maiju_bahal_chabahil", "chabahil", "gopi_krishna", "dhumbarahi", "narayan_gopal_chowk", "tu_teaching", "police_academy", "baluwatar", "kalika_tower_baluwatar", "rastrya_bank_baluwatar", "naxal_bbsm", "tangal", "naxal", "narayan_chaur", "nagpokhari", "hattisar", "putalisadak", "sankhar_dev_campus", "new_plaza", "anamnagar", "hanumansthan", "anamnagar_bbsm", "thapagaun", "baneshwor_panitanki", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari", "monohara_corridor_police_section", "boje_pokhari_bridge_manohara", "mahalaxmi_tikathali", "bhagwati_mandir_tikathali", "jhikuchu_tikathali", "bigmart_tikathali", "panitanki_tikathali", "tikathali"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["tikathali", "panitanki_tikathali", "bigmart_tikathali", "jhikuchu_tikathali", "bhagwati_mandir_tikathali", "mahalaxmi_tikathali", "boje_pokhari_bridge_manohara", "monohara_corridor_police_section", "balkumari", "koteshwor_bhatbhateni", "koteshwor", "koteshwor_bhaktapur_stop", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "baneshwor_panitanki", "thapagaun", "anamnagar_bbsm", "hanumansthan", "anamnagar", "new_plaza", "sankhar_dev_campus", "putalisadak", "hattisar", "nagpokhari", "narayan_chaur", "naxal", "tangal", "naxal_bbsm", "rastrya_bank_baluwatar", "kalika_tower_baluwatar", "baluwatar", "police_academy", "tu_teaching", "narayan_gopal_chowk", "dhumbarahi", "gopi_krishna", "chabahil", "maiju_bahal_chabahil", "shanti_goreto_chabahil", "chuchhepati", "mahankal", "ramsterdam_cafe_mahankal", "mugum_gumbha_mahankal", "bajranagar", "mandala_banquet_mahankal", "faika_chowk", "sanima_bank_faika", "kharibot_faika", "aani_gumba_kapan", "dhaulagiri_chowk", "banglamukhi_kapan", "kapan"] },

  // Route 17 (Ghantaghar ⇄ Mulpani Nepal Yatayat)
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["mulpani_nepal_yatayat", "milan_chowk", "baba_chowk", "godhargaun", "gaurinath_chowk", "godhargaun_chowk", "mahantar", "dotel_dairy", "hatti_dada", "sundari_chowk", "khahare", "khahare_bus_stop", "seto_ghar", "pepsicola", "chhapro", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "maitighar", "supreme_court", "singha_durbar", "putalisadak", "skywalk_tower", "ghantaghar"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["ghantaghar", "bhrikutimandap", "sahid_gate", "tripureshwor", "kantipur_park_thapathali", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "chhapro", "pepsicola", "seto_ghar", "khahare_bus_stop", "khahare", "sundari_chowk", "hatti_dada", "dotel_dairy", "mahantar", "godhargaun_chowk", "gaurinath_chowk", "godhargaun", "baba_chowk", "milan_chowk", "mulpani_nepal_yatayat"] },

  // ================= RIDDHI SIDDHI YATAYAT =================

  // Route 18 (Harisiddhi ⇄ RNAC)
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["riddhi_siddhi_harisiddhi", "lakhur_chowk", "harisiddhi_naya_basti", "siddhipur_drinking_water", "siddhipur_height_gate", "thasikwa_falcha", "buddha_pokhari", "imadol_tempo_park", "imadol_kamalpokhari", "mahalaxmi_municipality", "imadol_kharibot", "imadol_krishna_mandir", "imadol_pipalbot", "rata_makai_chowk", "kist_hospital", "gwarko_chowk(imadol side)", "gwarko", "balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "sahid_gate", "RNAC"] },
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["RNAC", "ratnapark", "tudikhel", "bhrikutimandap", "singha_durbar", "supreme_court", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pool", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "gwarko_chowk(imadol side)", "kist_hospital", "rata_makai_chowk", "imadol_pipalbot", "imadol_krishna_mandir", "imadol_kharibot", "mahalaxmi_municipality", "imadol_kamalpokhari", "imadol_tempo_park", "buddha_pokhari", "thasikwa_falcha", "siddhipur_height_gate", "siddhipur_drinking_water", "harisiddhi_naya_basti", "lakhur_chowk", "riddhi_siddhi_harisiddhi"] },

  // Route 19 (Mulpani ⇄ Thankot)
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["riddhi_siddhi_chandragiri", "baadbhanjyan(thankot)", "kharibot(thankot)", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul", "naikap", "tinthana", "dhungeadda", "kalanki", "kalanki_chowk", "kalanki_mandir", "ravi_bhawan", "soltimod", "kalimati", "teku", "tripureshwor", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "koteshwor", "jadibutti", "chhapro", "pepsicola", "pepsicola_chowk", "pepsicola_town_planning", "sunrise_chowk", "suncity", "laure_chowk", "harhar_mahadev_temple", "bista_gaun", "christian_school", "mulpani_volleyball_centre", "mulpani_chaur", "sunrise_bakery_mulpani", "riddhi_siddhi_mulpani"] },
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["riddhi_siddhi_mulpani", "sunrise_bakery_mulpani", "mulpani_chaur", "mulpani_volleyball_centre", "mulpani_pipalbot", "christian_school", "bista_gaun", "harhar_mahadev_temple", "laure_chowk", "suncity", "sunrise_chowk", "pepsicola_town_planning", "pepsicola_chowk", "pepsicola", "chhapro", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "thapathali", "tripureshwor", "teku", "kalimati", "soltimod", "ravi_bhawan", "kalanki_mandir", "kalanki_chowk", "kalanki", "dhungeadda", "tinthana", "naikap", "balkhu_pul", "satungal", "gurjudhara", "thankot_checkpost", "thankot", "kharibot(thankot)", "baadbhanjyan(thankot)", "riddhi_siddhi_chandragiri"] },

  //================= GOKARNESHWOR YATAYAT =================
  // Route 20
  //ROUTE 20(Gokarneshwor ⇄ Ring Road )
  { vehicle: "bus", company: "Gokarneshwor Yatayat", stops: ["gopi_krishna","dhumbarahi", "chhapal_karkhana", "narayan_gopal_chowk", "chiray_hospital", "basundhara", "samakhusi", "gongabu_chowk", "machha_pokhari", "balaju", "banasthali", "dhungedhara", "sano_bharyang", "thulo_bharyang", "swayambhu", "sitapaila", "bafal", "kalanki_makalu_stop", "khasi_bazar", "advanced_college_of_engineering", "balkhu", "sanepa", "star_hospital", "dhobigat", "nakhu", "ekantakuna", "kusunti", "mahalaxmisthan", "talchikhel", "chapagaun_dobato", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko","balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "koteshwor_bhaktapur_stop", "tinkune", "sinamangal_Ooralo", "sinamangal", "airport", "tilganga_eye_hospital", "pashupati_temple", "gaushala", "jay bageshwori", "mitrapark", "chabahil","chuchepati","bouddha_stupa","jorpati","narayanthan","dakshindhoka","jaya_multiple_campus","makalbari_bridge","gokarneshwor"]},
  { vehicle: "bus", company: "Gokarneshwor Yatayat", stops: ["gokarneshwor","makalbari_bridge","jaya_multiple_campus","dakshindhoka","narayantar","jorpati","bouddha_stupa","chuchepati","chabahil", "mitrapark", "jay bageshwori", "gaushala", "pashupati_temple", "tilganga_eye_hospital", "airport", "sinamangal", "sinamangal_Ooralo", "tinkune", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pul", "balkumari", "balkumari_kharibot", "royal_tulip_hotel","gwarko","satdobato_swimming_pool", "satdobato", "chapagaun_dobato", "talchikhel", "mahalaxmisthan", "kusunti", "ekantakuna", "nakhu", "dhobigat", "star_hospital", "sanepa", "balkhu", "advanced_college_of_engineering", "khasi_bazar", "kalanki_makalu_stop", "bafal", "sitapaila", "swayambhu", "thulo_bharyang", "sano_bharyang", "dhungedhara", "banasthali", "balaju", "machha_pokhari", "gongabu_chowk", "samakhusi", "basundhara", "chiray_hospital", "narayan_gopal_chowk", "chhapal_karkhana", "dhumbarahi", "gopi_krishna"]},
];