const routes = [
  // ================= SAJHA YATAYAT =================
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["baadbhanjyan", "kharibot", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul", "naikap", "tinthana", "dhungeadda", "kalanki", "kalanki_chowk", "kalanki_mandir", "ravi_bhawan", "soltimod", "kalimati", "teku", "tripureshwor", "bhadrakali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "tinkune", "sinamangal_ooralo", "sinamangal", "airport"] },

  { vehicle: "bus", company: "Sajha Yatayat", stops: ["airport", "sinamangal", "sinamangal_ooralo", "tinkune", "bubhidhanagar", "santinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "sahid_gate", "tripureshwor", "teku", "kalimati", "soltimod", "ravi_bhawan", "kalanki_mandir", "kalanki_chowk", "kalanki", "dhungeadda", "tinthana", "naikap", "balkhu_pul", "satungal", "gurjudhara", "thankot_checkpost", "thankot", "kharibot", "baadbhanjyan"] },

  // ROUTE 1
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["naya_bus_park", "gongabu", "samakhusi", "basundhara", "chiray_hospital", "narayan_gopal_chowk", "us_embassy", "tu_teaching_hospital", "police_academy", "panipokhari", "radission_hotel", "lazimpat", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lagankhel", "kuparipati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "tripureshwor", "RNAC", "radission_hotel", "lazimpat", "panipokhari", "police_academy", "tu_teaching_hospital", "us_embassy", "narayan_gopal_chowk", "chiray_hospital", "basundhara", "samakhusi", "gongabu", "naya_bus_park"] },

  // ROUTE 2
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["budhanilkantha", "narayanthan", "deuba_chowk", "naya_chowk", "rudreshwor_chowk", "chapali_ghumti", "ganesh_chowk", "hattigauda_chowk", "golfutar", "neuro_hospital", "gangalal_hospital", "bansbari", "narayan_gopal_chowk", "us_embassy", "tu_teaching_hospital", "police_academy", "panipokhari", "radission_hotel", "lazimpat", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lagankhel", "kuparipati", "jawalakhel", "pulchowk", "harihar_bhawan", "kupondole", "tripureshwor", "RNAC", "radission_hotel", "lazimpat", "panipokhari", "police_academy", "tu_teaching_hospital", "us_embassy", "narayan_gopal_chowk", "bansbari", "gangalal_hospital", "neuro_hospital", "golfutar", "hattigauda", "ganesh_chowk", "chapali_ghumti", "rudreshwor_chowk", "naya_chowk", "deuba_chowk", "narayanthan", "budhanilkantha"] },

  // ROUTE 3
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["nagdhunga", "baadbhanjyan", "kharibot", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul", "naikap", "tinthana", "dhungeadda", "kalanki_makalu_stop", "bafal", "sitapaila", "swayambhu", "thulo_bharyang", "sano_bharyang", "dhungedhara", "banasthali", "balaju", "machhapokhari", "gongabu", "samakhusi", "basundhara", "chiray_hospital", "bansbari", "narayan_gopal_chowk", "gangalal_hospital", "neuro_hospital", "golfutar", "hattigauda_chowk", "ganesh_chowk", "chapali_ghumti", "rudreshwor_chowk", "naya_chowk", "deuba_chowk", "narayanthan", "budhanilkantha"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["budhanilkantha", "narayanthan", "deuba_chowk", "naya_chowk", "rudreshwor_chowk", "chapali_ghumti", "ganesh_chowk", "hattigauda_chowk", "golfutar", "neuro_hospital", "gangalal_hospital", "bansbari", "narayan_gopal_chowk", "chiray_hospital", "basundhara", "samakhusi", "gongabu", "machha_pokhari", "balaju", "banasthali", "dhungedhara", "sano_bharyang", "thulo_bharyang", "swayambhu", "sitapaila", "bafal", "kalanki_makalu_stop", "dhungeadda", "tinthana", "naikap", "balkhu_pul", "satungal", "gurjudhara", "thankot_checkpost", "thankot", "kharibot", "baadbhanjyan", "nagdhunga"] },

  // ROUTE 5
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel_chowk", "jawalakhel", "ekantakuna", "vaishnavi_devi", "nakhu", "nakhu_pul", "phulbari", "charghari", "bhaisepati", "sainbu", "mahila_ghar", "kalika", "wai_wai_factory", "khokana", "adarsha_saula_school", "chyasikote", "bungamati"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["bungamati", "chyasikote", "adarsha_saula_school", "khokana", "wai_wai_factory", "kalika", "mahila_ghar", "sainbu", "bhaisepati", "charghari", "phulbari", "nakhu_pul", "nakhu", "vaishnavi_devi", "ekantakuna", "jawalakhel", "jawalakhel_chowk", "pulchowk", "harihar_bhawan", "jawagal_chowk", "kupondole", "tripureshwor", "RNAC", "jamal"] },

  // ROUTE 6
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["RNAC", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel", "satdobato(lagankhel side)", "satdobato(godawari side)", "dhapakhel_dobato", "hattiban", "harishiddhi", "thaiba", "badegaun", "hadegaun", "toukhel", "godawari"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["godawari", "toukhel", "hadegaun", "sadegaun", "thaiba", "harishiddhi", "hattiban", "dhapakhel_dobato", "satdobato(godawari side)", "satdobato(lagankhel side)", "lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "jawagal_chowk", "kupondole", "tripureshwor", "RNAC"] },

  // ROUTE 7
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel", "satdobato(lagankhel side)", "satdobato", "chapagaun_dobato", "loktantrik_chowk", "janani_marga", "pragati_chowk", "dholahiti", "simako_chowk", "NTC_thecho", "thecho", "jhyal_pati", "chapagaun", "pyangaun", "bhageshwori", "tikabhairav", "champeshwori_temple", "lele_bus_park"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["lele_bus_park", "champeshwori_temple", "tikabhairav", "bhageshwori", "pyangaun", "chapagaun", "jhyal_pati", "thecho", "NTC_thecho", "simako_chowk", "dholahiti", "pragati_chowk", "janani_marga", "loktantrik_chowk", "chapagaun_dobato", "satdobato(lagankhel side)", "lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "jawagal_chowk", "kupondole", "tripureshwor", "RNAC", "jamal"] },

  // ROUTE 8
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["naya_bus_park", "gongabu", "samakhusi", "basundhara", "chiray_hospital", "narayan_gopal_chowk", "us_embassy", "tu_teaching_hospital", "police_academy", "panipokhari", "radission_hotel", "lazimpat", "jamal", "bhrikutimandap", "sahid_gate", "tripureshwor", "thapathali", "kupondole", "jawagal_chowk", "harihar_bhawan", "pulchowk", "jawalakhel", "kumaripati", "lagankhel", "satdobato(lagankhel side)", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko", "gwarko_chowk(imadol side)", "kist_hospital", "rata_makai_chowk", "imadol_pipalbot", "imadol_krishna_mandir", "imadol_kharibot", "mahalaxmi_municipality", "imadol_kamalpokhari", "imadol_tempo_park", "goalbhatta", "bhatbhateni_siddhipur", "sanagaun", "narkate_chowk", "kwo_lachhi", "lubhu", "mahalaxmi_campus", "lamatar", "dhungin"] },
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["dhungin", "lamatar", "mahalaxmi_campus", "lubhu", "kwo_lachhi", "narkate_chowk", "sanagaun", "bhatbhateni_siddhipur", "goalbhatta", "imadol_tempo_park", "imadol_kamalpokhari", "mahalaxmi_municipality", "imadol_kharibot", "imadol_krishna_mandir", "imadol_pipalbot", "rata_makai_chowk", "kist_hospital", "gwarko_chowk(imadol side)", "gwarko", "satdobato_swimming_pool", "satdobato", "satdobato(lagankhel side)", "lagankhel", "kumaripati", "jawalakhel", "pulchowk", "harihar_bhawan", "jawagal_chowk", "kupondole", "tripureshwor", "RNAC", "lazimpat", "radission_hotel", "panipokhari", "police_academy", "tu_teaching_hospital", "us_embassy", "narayan_gopal_chowk", "chiray_hospital", "basundhara", "samakhusi", "gongabu", "naya_bus_park"] },

  // ROUTE 9
  { vehicle: "bus", company: "Sajha Yatayat", stops: ["milan_chowk", "baba_chowk", "godharthapa_chowk", "khursani_chowk", "pipalbot_chowk", "adarsha_tol", "mantar_chowk", "gothatar", "pepsi_cola_chowk", "jadibutti", "tinkune_subidhanagar", "minbhawan", "new_baneshwor", "bijuli_bazar", "maitighar", "putalisadak", "kamladi", "bhrikutimandap"] },

  // ================= BHAKTAPUR YATAYAT =================
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kausaltar", "lockanthali", "jadibutti", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pul", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "satdobato_swimming_pool", "satdobato", "chapagaun_dobato", "talchikhel", "mahalaxmisthan", "kusunti", "ekantakuna", "nakhu", "dhobigat", "star_hospital", "sanepa", "balkhu", "advance_college_of_engineering", "khashi_bazar", "kalanki_makalu_stop"] },

  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kausaltar", "lockanthali", "jadibutti", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pul", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "satdobato_swimming_pool", "satdobato", "lagankhel"] },
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["lagankhel", "satdobato(godawari side)", "satdobato", "satdobato_swimming_pool", "B&B_hospital", "gwarko", "balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "jadibutti", "lockanthali", "kausaltar", "gatthagar", "chardobato", "tuberculosis_hospital", "thimi", "radhe radhe", "srijan_nagar", "sallaghari", "chundevi", "suryabinayak", "jagati", "dhara", "chaymasing", "kamalbinayak"] },

  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["kamalbinayak", "chaymasing", "dhara", "jagati", "suryabinayak", "chundevi", "sallaghari", "srijan_nagar", "radhe radhe", "thimi", "tuberculosis_hospital", "chardobato", "gatthagar", "kausaltar", "lockanthali", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "sahid_gate", "RNAC"] },
  { vehicle: "bus", company: "Bhaktapur Yatayat", stops: ["RNAC", "ratnapark", "tudikhel", "bhrikutimandap", "singha_durbar", "supreme_court", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "lockanthali", "kausaltar", "gatthagar", "chardobato", "tuberculosis_hospital", "thimi", "radhe radhe", "srijan_nagar", "sallaghari", "chundevi", "suryabinayak", "jagati", "dhara", "chaymasing", "kamalbinayak"] },

  // ================= NEPAL YATAYAT =================
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["balkhu", "sanepa", "star_hospital", "dhobigat", "nakhu", "ekantakuna", "jawalakhel", "jawalakhel_chowk", "pulchowk", "harihar_bhawan", "kupondole", "kantipur_park_thapathali", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "chhapro", "pepsicola", "pepsicola_chowk", "pepsicola_town_planning", "sunrise_chowk", "suncity", "laure_chowk", "harhar_mahadev_temple", "harhar_mahadev"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["harhar_mahadev", "harhar_mahadev_temple", "laure_chowk", "suncity", "sunrise_chowk", "pepsicola_town_planning", "pepsicola_chowk", "pepsicola", "chhapro", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "thapathali", "tripureshwor", "teku", "kalimati", "gobal_ime_kuleshwor", "nabil_kuleshwor", "kitab_kalam_kuleshwor", "balkhu"] },

  { vehicle: "bus", company: "Nepal Yatayat", stops: ["kapan", "banglamukhi_kapan", "dhaulagiri_chowk", "aani_gumba_kapan", "kharibot_faika", "sanima_bank_faika", "faika_chowk", "mandala_banquet_mahankal", "bajranagar", "mugum_gumbha_mahankal", "ramsterdam_cafe_mahankal", "mahankal", "chuchhepati", "shanti_goreto_chabahil", "maiju_bahal_chabahil", "chabahil", "gopi_krishna", "dhumbarahi", "narayan_gopal_chowk", "tu_teaching", "police_academy", "baluwatar", "kalika_tower_baluwatar", "rastrya_bank_baluwatar", "naxal_bbsm", "tangal", "naxal", "narayan_chaur", "nagpokhari", "hattisar", "putalisadak", "sankhar_devi_campus", "new_plaza", "anamnagar", "hanumansthan", "anamnagar_bbsm", "thapagaun", "baneshwor_panitanki", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari", "monohara_corridor_police_section", "boje_pokhari_bridge_manohara", "mahalaxmi_tikathali", "bhagwati_mandir_tikathali", "jhikuchu_tikathali", "bigmart_tikathali", "panitanki_tikathali", "tikathali"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["tikathali", "panitanki_tikathali", "bigmart_tikathali", "jhikuchu_tikathali", "bhagwati_mandir_tikathali", "mahalaxmi_tikathali", "boje_pokhari_bridge_manohara", "monohara_corridor_police_section", "balkumari", "koteshwor_bhatbhateni", "koteshwor", "koteshwor_bhaktapur_stop", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "baneshwor_panitanki", "thapagaun", "anamnagar_bbsm", "hanumansthan", "anamnagar", "new_plaza", "sankhar_devi_campus", "putalisadak", "hattisar", "nagpokhari", "narayan_chaur", "naxal", "tangal", "naxal_bbsm", "rastrya_bank_baluwatar", "kalika_tower_baluwatar", "baluwatar", "police_academy", "tu_teaching", "narayan_gopal_chowk", "dhumbarahi", "gopi_krishna", "chabahil", "maiju_bahal_chabahil", "shanti_goreto_chabahil", "chuchhepati", "mahankal", "ramsterdam_cafe_mahankal", "mugum_gumbha_mahankal", "bajranagar", "mandala_banquet_mahankal", "faika_chowk", "sanima_bank_faika", "kharibot_faika", "aani_gumba_kapan", "dhaulagiri_chowk", "banglamukhi_kapan", "kapan"] },

  { vehicle: "bus", company: "Nepal Yatayat", stops: ["mulpani_nepal_yatayat", "milan_chowk", "baba_chowk", "godhargaun", "gaurinath_chowk", "godhargaun_chowk", "mahantar", "dotel_dairy", "hatti_dada", "sundari_chowk", "khahare", "khahare_bus_stop", "seto_ghar", "pepsicola", "chhapro", "jadibutti", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "maitighar", "supreme_court", "singha_durbar", "putalisadak", "skywalk_tower", "ghantaghar"] },
  { vehicle: "bus", company: "Nepal Yatayat", stops: ["ghantaghar", "bhrikutimandap", "sahid_gate", "tripureshwor", "kantipur_park_thapathali", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "jadibutti", "chhapro", "pepsicola", "seto_ghar", "khahare_bus_stop", "khahare", "sundari_chowk", "hatti_dada", "dotel_dairy", "mahantar", "godhargaun_chowk", "gaurinath_chowk", "godhargaun", "baba_chowk", "milan_chowk", "mulpani_nepal_yatayat"] },

  // ================= RIDDHI SIDDHI YATAYAT =================
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["riddhi_siddhi_harisiddhi", "lakhur_chowk", "harisiddhi_naya_basti", "siddhipur_drinking_water", "siddhipur_height_gate", "thasikwa_falcha", "buddha_pokhari", "imadol_tempo_park", "imadol_kamalpokhari", "mahalaxmi_municipality", "imadol_kharibot", "imadol_krishna_mandir", "imadol_pipalbot", "rata_makai_chowk", "kist_hospital", "gwarko_chowk(imadol side)", "gwarko", "balkumari_kharibot", "balkumari", "balkumari_pool", "koteshwor_bhatbhateni", "koteshwor", "subhidhanagar", "shantinagar", "civil_hospital", "new_baneshwor", "bijuli_bazar", "babar_mahal", "maitighar", "bhadrakali", "sahid_gate", "RNAC"] },
  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["RNAC", "ratnapark", "tudikhel", "bhrikutimandap", "singha_durbar", "supreme_court", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "subhidhanagar", "koteshwor_bhaktapur_stop", "koteshwor", "koteshwor_bhatbhateni", "balkumari_pul", "balkumari", "balkumari_kharibot", "royal_tulip_hotel", "gwarko", "gwarko_chowk(imadol side)", "kist_hospital", "rata_makai_chowk", "imadol_pipalbot", "imadol_krishna_mandir", "imadol_kharibot", "mahalaxmi_municipality", "imadol_kamalpokhari", "imadol_tempo_park", "buddha_pokhari", "thasikwa_falcha", "siddhipur_height_gate", "siddhipur_drinking_water", "harisiddhi_naya_basti", "lakhur_chowk", "riddhi_siddhi_harisiddhi"] },

  { vehicle: "bus", company: "Riddhi Siddhi Yatayat", stops: ["baadbhanjyan", "kharibot", "thankot", "thankot_checkpost", "gurjudhara", "satungal", "balkhu_pul", "naikap", "tinthana", "dhungeadda", "kalanki", "kalanki_chowk", "kalanki_mandir", "ravi_bhawan", "soltimod", "kalimati", "teku", "tripureshwor", "thapathali", "maitighar", "babar_mahal", "bijuli_bazar", "new_baneshwor", "civil_hospital", "shantinagar", "koteshwor", "jadibutti", "chhapro", "pepsicola", "pepsicola_chowk", "pepsicola_town_planning", "sunrise_chowk", "suncity", "laure_chowk", "harhar_mahadev_temple", "bista_gaun", "christian_school", "mulpani_volleyball_centre", "mulpani_chaur", "sunrise_bakery_mulpani", "riddhi_siddhi_mulpani"] }
];